sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: yarn
branches:
  only:
    - hexo # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    all_branches: true # solve a permission problem
    target_branch: master
    # branch: master
  local-dir: public
